[project]
name = "crash-punks-v2"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.digital-avatar]
path = "contracts/digital-avatar.clar"

[contracts.hardware-top-example]
path = "contracts/hardware-top-example.clar"

[contracts.hypercard]
path = "contracts/hypercard.clar"

[contracts.snow]
path = "contracts/snow.clar"

[contracts.staking]
path = "contracts/staking.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
